[[constraint]]
  name = "github.com/cubex/cubeutil-go"
  version = "~0.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.8"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.12"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
